// Code->name pairs mirror ALL_COUNTRIES in app/onboarding/candidate/page.tsx (which also
// carries dialCode/flag for the phone picker — keep both lists in sync if a country is
// added/removed).
export const COUNTRY_NAMES: Record<string, string> = {
  IN: 'India',
  US: 'United States',
  CA: 'Canada',
  GB: 'United Kingdom',
  AU: 'Australia',
  DE: 'Germany',
  FR: 'France',
  IT: 'Italy',
  ES: 'Spain',
  JP: 'Japan',
  CN: 'China',
  BR: 'Brazil',
  MX: 'Mexico',
  ZA: 'South Africa',
  SG: 'Singapore',
  NL: 'Netherlands',
  NZ: 'New Zealand',
  CH: 'Switzerland',
  SE: 'Sweden',
  NO: 'Norway',
  DK: 'Denmark',
  FI: 'Finland',
  BE: 'Belgium',
  AT: 'Austria',
  IE: 'Ireland',
  PT: 'Portugal',
  GR: 'Greece',
  TR: 'Turkey',
  SA: 'Saudi Arabia',
  AE: 'UAE',
  IL: 'Israel',
  EG: 'Egypt',
  NG: 'Nigeria',
  KE: 'Kenya',
  AR: 'Argentina',
  CO: 'Colombia',
  CL: 'Chile',
  PE: 'Peru',
  MY: 'Malaysia',
  ID: 'Indonesia',
  PH: 'Philippines',
  TH: 'Thailand',
  VN: 'Vietnam',
  HK: 'Hong Kong',
  TW: 'Taiwan',
  KR: 'South Korea',
  PK: 'Pakistan',
  BD: 'Bangladesh',
  LK: 'Sri Lanka',
  UA: 'Ukraine',
  PL: 'Poland',
  RO: 'Romania',
  HU: 'Hungary',
  CZ: 'Czech Republic',
  SK: 'Slovakia',
  HR: 'Croatia',
  BG: 'Bulgaria',
  RS: 'Serbia',
  SI: 'Slovenia',
  LT: 'Lithuania',
  LV: 'Latvia',
  EE: 'Estonia',
  MA: 'Morocco',
  DZ: 'Algeria',
  TN: 'Tunisia',
  GH: 'Ghana',
  ET: 'Ethiopia',
  TZ: 'Tanzania',
  UG: 'Uganda',
  JO: 'Jordan',
  LB: 'Lebanon',
  KW: 'Kuwait',
  QA: 'Qatar',
  BH: 'Bahrain',
  OM: 'Oman',
  KZ: 'Kazakhstan',
  UZ: 'Uzbekistan',
};
